[versions]
# libraries

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.2.1"
kotlin = "2.2.0"
kover = "0.9.1"
serialization = "2.2.0"

[libraries]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
