[versions]
# libraries
junit = "4.13.2"
mockk = "1.13.16"
kotlinProcess = "1.5"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.2.1"
kotlin = "2.1.20"
kover = "0.8.3"
serialization = "2.0.20"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk-jvm", version.ref = "mockk" }
kotlinProcess = { group = "com.github.pgreze", name = "kotlin-process", version.ref = "kotlinProcess" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
